### ISSUE TITLE
Infinitley no signal

### ISSUE THREAD

**Issue by yuckdev2** [mbcrump/PS4900Linux#1]
When I load the second payload it just goes to no signal. Why is this. The PS4 stays on with a white light but doesn't send a signal.

**Comment by yuckdev2** [comment]
This is on PS4 Pro.

**Comment by mbcrump** [comment]
@atomic-ozzy-original - I'm not sure you should post this in a forum where a lot of other folks will see - https://www.reddit.com/r/ps4homebrew/
